### PR TITLE
faq/tou/404/person page updates / bugfixes - addresses #169

### PR DESCRIPTION
**Pull request by UcDust**
This includes updates for the following:
-404 same as before, ie https://rc.experts.ucdavis.edu/x
-Terms of Use
-FAQ, using https://brand.library.ucdavis.edu/#ucd-theme-list-accordion
-make person page more mobile layout like the search width breakpoint for mobile going to 80/90% or whatever
-mobile view for person page
-publications, alphabetical per year by title
-finish person work detail page and pagination, mobile styles

### CODE REVIEW

**Review by qjhart — APPROVED** [review]

**Comment by qjhart** [comment]
@Vensberg I'm add this PR as a location to check 

- [ ] 404
- [ ] FAQ
- [ ] TOU

If they all look good, remove yourself and notice me below.   I'd suggest it's a good idea to add another sheet to the [User Test](https://docs.google.com/spreadsheets/d/1X2W-ohJwtblfGdXdA7lAJJn2sqKvS9tIEd8sR3aospY/edit?usp=sharing) that has additional pages to check

**Comment by Vensberg** [comment]
404 is not on Sandbox

**Comment by Vensberg** [comment]
TOU needs new content

**Comment by UcDust** [comment]
@Vensberg 

Which url were you trying to see the 404? I tested some invalid urls, like `/x`, `/unknown-page`, etc., and it seems to show the 404-

Screenshot 2023-10-05 at 06 40 10

**Comment by Vensberg** [comment]
I tested it at https://sandbox.experts.library.ucdavis.edu/person/x. Now I can see it shows up for everything else except for this.

**Comment by UcDust** [comment]
@Vensberg 
Great, thanks! I see what you mean now. 

So I think the `person/x`, `works/x` and `grants/x` pages will need a little more code added to load the 404 when subpages don't exist. It's not triggering the 404 because of how the page routing is configured. 

I'll add this in with my next group of commits and let you know.

**Comment by Vensberg** [comment]
@UcDust , this is the updated Terms of Use https://docs.google.com/document/d/1BX3Hds1tril48x0wv-NiIBXzf7ldIHVTU9MFy6dWpQQ/edit#heading=h.3znysh7

**Comment by UcDust** [comment]
@Vensberg 

The Terms of Use page should be updated now, and the 404 should also display when navigating to invalid person id's.

**Comment by Vensberg** [comment]
@UcDust , just one more landing page that needs to give a 404 for now: https://sandbox.experts.library.ucdavis.edu/works/ (without the slash it renders correctly as 404, but with it, it gives a page with 0 works. Eventually, this will be a works browse, but for now, it should be 404. Unless we want it to be under construction?. @wrenaria , if we know a page will eventually contain  data, is it better to have an "under construction" note or should it be 404 until ready?

**Comment by UcDust** [comment]
@Vensberg @wrenaria 

Actually I think this page is currently used to display works for a particular user. Using the link to `SEE ALL WORKS` from the person page. For instance, https://sandbox.experts.library.ucdavis.edu/works/person/66356b7eec24c51f01e757af2b27ebb8.

So essentially it's /works/<personId>.

I could update that so it throws a 404 if no personId match is found though. I'll see if I can sneak that into the next commit and let you know.

**Comment by UcDust** [comment]
@Vensberg 

Ok so that `/works/` route should now throw the 404.

**Comment by Vensberg** [comment]
Awesome. 404 is complete. I'll work on additional text for FAQ today.

**Comment by Vensberg** [comment]
@wrenaria can you take a look at Terms of Use and sign off on it? https://sandbox.experts.library.ucdavis.edu/termsofuse

**Comment by Vensberg** [comment]
@UcDust , here is the updated content for the FAQs: https://docs.google.com/document/d/1mvCuOP7339W7_DeHyC74HLSO7z4k1F_wy3k1TAhCYCQ/edit

**Comment by wrenaria** [comment]
@Vensberg 
> @wrenaria , if we know a page will eventually contain data, is it better to have an "under construction" note or should it be 404 until ready?

There is mixed opinions on this, but I'm generally of the opinion that if content doesn't exist it's better for the page to not exist until there is content for it. If you wanted to do an under construction page, it ought to be useful to the user somehow -- for example, tell the user what the page will become and link to project info / timeline or something. But since this is our first public launch, I think its better for pages that don't exist yet to just not be.

**Comment by Vensberg** [comment]
Sounds good, let's keep 404.

**Comment by UcDust** [comment]
@Vensberg 
The last change to the FAQ should be published to sandbox now.

**Pull request merged**
