### PR TITLE
split bundles by page to improve performance #514

### PR DESCRIPTION
**Pull request by UcDust**

### CODE REVIEW

**Comment by UcDust** [comment]
@qjhart 
This is just for the webpack bundles in the client.
I also created https://github.com/ucd-library/aggie-experts/issues/513 for next sprint to address tuning the api response data.

**Comment by qjhart** [comment]
@UcDust should justin look over this, or are you confident you've addressed his concerns?

**Comment by UcDust** [comment]
@qjhart I'm pretty sure things are working as he wants them, but it wouldn't hurt to ask. Mind looked at this PR @jrmerz?

I replicated the pattern in the previous RP repo, and navigating around the various pages, you can see the respective smaller bundle files being loaded.

**Comment by UcDust** [comment]
@qjhart this should be ready now, I've updated the `dist` webpack scripts so it copies the files from the `public` folder.

**Review by qjhart — APPROVED** [review]

**Pull request merged**
