### PR TITLE
redirect edit of intro/links directly to profile page of elements

### PR DESCRIPTION
**Pull request by UcDust**

### CODE REVIEW

**Review by qjhart — APPROVED** [review]

**Comment by Vensberg** [comment]
Can you make it land on the profile in edit mode (em=true)?
Also, have it open in a new tab, not in the same window.

**Comment by UcDust** [comment]
@Vensberg 
I can adjust that. Do you want editing _Roles_ and _Name_ to also open in new tab?

**Comment by Vensberg** [comment]
@UcDust yes, please. Just to confirm, for now Roles and Names stay with ODR.

**Comment by UcDust** [comment]
@UcDust will do, and yes that's correct.

**Comment by UcDust** [comment]
@Vensberg this should be ready for review on test.

**Comment by Vensberg** [comment]
@UcDust ---looks good

- [x] opens in a new tab
- [x] opens Elements profile in edit mode

**Pull request merged**
