### PR TITLE
add browse by a-z with new /api/browse routes #220, grants pagination…

### PR DESCRIPTION
**Pull request by UcDust**
… #169

### CODE REVIEW

**Comment by UcDust** [comment]
This addresses the following items:

-browse by with new api
-browse by to load available letters, and disable in the ui if no results for a letter
-grants/citations, visibility and reject. Can’t reject grants. remove reject button
-browse by, get pagination working
-fix grants pagination list page
-fix grants pagination edit page
-is-visible for grants and citations on expert page, throw error in console if not true

**Review by qjhart — APPROVED** [review]

**Comment by Vensberg** [comment]
Definition of Done for Experts A-Z browse

- [x] Clicking on Experts in the menu takes the user to the Browse setup
- [ ] Last names are under the correct letter
- [ ] Names paginate properly (check M, since it has >25 names)
- [ ] Name, role and department are shown
- [ ] Clicking on the expert's name takes the user to the expert's profile
- [ ] Every letter starts from page 1

**Comment by Vensberg** [comment]
@UcDust , for Experts Browse A-Z, when I click on M, then go to page 2, then click on N (or another letter), I land on page 2 for N. Each letter should start on the equivalent of its page 1.

**Comment by UcDust** [comment]
@Vensberg good catch! I'll have this patched in a bit.

**Comment by UcDust** [comment]
@Vensberg that fix should be live on sandbox now.

**Comment by Vensberg** [comment]
@UcDust, Expert pagination looks good. 

There is a smaller similar issue with grants pagination. If I click on page 2 of grants, then click on "return to profile" then click back on grants, page 2 opens up. This happens even if I navigate to multiple pages in between returning to "see all grants".

**Comment by UcDust** [comment]
@Vensberg I'll get that into the next deployment and let you know.

**Pull request merged**
