### PR TITLE
Add grant relationship gets

### PR DESCRIPTION
**Pull request by rakunkel-ucd**
Factors to consider:
- In some cases, PIs will be retired, etc. (missing PIs)
- Should we just include a list of all co-PIs?
- Where to store cache XML of the grant relations.
- Update experts bind to skip relationship users.

### CODE REVIEW

**Comment by Vensberg** [comment]
Yes, all PIs should be included in the data pull. At a later time, the grant landing page is going to include a list of UC and non-UC contributors.

**Comment by qjhart** [comment]
> Yes, all PIs should be included in the data pull. At a later time, the grant landing page is going to include a list of UC and non-UC contributors.

@Vensberg So here's the problem.  The KFS system, uses their own database of users.  These users don't necessarily need to be in either the campus IAM, or CDL elements.  So, we only really have the textual Name of the PI for sure.  

In KFS there is only 1 PI.  there can be multiple Co-PIs.  We are only really sure of the PI.

For example, for the Grant "COMET: COST-TO-MOUNTAIN ENVIRONMENTAL TRANSECT",  Bertram Ludaescher was the PI, and I was a Co-PI, though that doesn't come thru on the KFS pull, and Bertram doesn't exist in IAM or CDL since he's long gone. 

So, I suggest that we include a *text* field that lists *only* the PI, and then we can add that to every grant, but we do not try and add all the contributors, because there may be many, and we might not know them all.

When we move to a grant specific page, we can then have the PI and all the contributors that are still in the system.

**Comment by rakunkel-ucd** [comment]
I think this PR should be closed as this branch is out of date.

**Comment by rakunkel-ucd** [comment]
Single commit was made in error.

**Pull request closed without merging**
