### PR TITLE
add loading for hide/show/delete of expert, show expert sections with…

### PR DESCRIPTION
**Pull request by UcDust**
… no data when editing

### CODE REVIEW

**Comment by UcDust** [comment]
This will include updates for the following:

- [ ] [This comment](https://github.com/ucd-library/aggie-experts/pull/358#issuecomment-1998590946) @Vensberg mentions changing "private" to "internal" in the delete modal for experts, as well as that the visibility icon was not updating until page refresh. I think the icon not changing was because the request to authenticate in CDL took a few seconds, so I added loading animations to the visibility/delete actions.
- [ ] @wrenaria mentioned to add _No data to display_ to sections of the expert profile if there is no content, so the user can navigate and populate this data. This will show up only when editing/impersonating.
- [ ] While testing the previous item, I noticed if you hide all works or grants, when editing/impersonating, the headers with links to edit the works/grants disappear. Now it will show _0 Works/Grants_ and show the hidden works/grants, and have links to the edit pages. 
- [ ] She also mentioned to update the _My Account_ quicklinks header nav to include a profile image for clarity.

**Review by qjhart — APPROVED** [review]

**Comment by Vensberg** [comment]
- [x] Changes in visibility in test AE successfully changes all aspects of the user's profile in QA Elements to internal, including relationships to works and grants


@UcDust , I'd like to rework the Hide Expert message content. Can you make it:
Expert will be hidden from Aggie Experts. In the Publication Management System their privacy will be set to internal. To show the expert again in Aggie Experts, you change the privacy in the Publication Management System to public or contact an Aggie Experts administrator. Are you sure you would like to continue?

**Comment by Vensberg** [comment]
@UcDust reversing from invisible to visible throws an error. Can you make that waiting period longer? It worked well for the invisible. 
I will hold on testing deletion, but their wait periods should probably be adjusted, too.

**Comment by Vensberg** [comment]
Now the invisible-->visible works

**Comment by Vensberg** [comment]
Based on https://github.com/ucd-library/aggie-experts/pull/358, the message for visible-->invisible should be:
The expert will be hidden from Aggie Experts, but this change will not appear in Elements. This is a safeguard available only to admins, in case "Delete Expert" does not work because Elements is not reachable. It is the admin's responsibility to manually change visibility in Elements.

Based on that, the connection between the visible icon and Elements should be removed.

**Comment by Vensberg** [comment]
For deletions, the message should be:
Expert will be removed from Aggie Experts. In the [UC Publication Management System](https://oapolicy.universityofcalifornia.edu/) their privacy will be set to internal.To show the expert again in Aggie Experts, you would need to update the privacy setting to public in the UC Publication Management System. Are you sure you would like to continue?

**Comment by UcDust** [comment]
@Vensberg this should be deployed to test for tomorrow.

**Comment by qjhart** [comment]
@Vensberg @UcDust , Not sure why Dusty marked here, this PR had been deployed. I did deploy #373, #374 however

**Pull request merged**
